package uz.ravshanbaxranov.mytaxi.util

object Constants {

    const val PERMISSION_LOCATION_REQUEST_CODE = 1
    const val PERMISSION_BACKGROUND_LOCATION_REQUEST_CODE = 2
    const val REQUEST_CHECK_SETTINGS = 1001

    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"

    const val NOTIFICATION_CHANNEL_ID = "tracker_notification_id"
    const val NOTIFICATION_CHANNEL_NAME = "tracker_notification"
    const val NOTIFICATION_ID = 3

    const val PENDING_INTENT_REQUEST_CODE = 99

    const val LOCATION_UPDATE_INTERVAL = 2000L
    const val LOCATION_UPDATE_MAXIMUM_INTERVAL = 4000L
    const val LOCATION_UPDATE_MINIMUM_INTERVAL = 1000L
    const val ACTION_SHOW_TRACKING_FRAGMENT = "ACTION_SHOW_TRACKING_FRAGMENT"


}

